/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AAndLogicalOr extends PLogicalOr
{
    private PLogicalOr _l_;
    private PLogicalOr _r_;

    public AAndLogicalOr()
    {
    }

    public AAndLogicalOr(
        PLogicalOr _l_,
        PLogicalOr _r_)
    {
        setL(_l_);

        setR(_r_);

    }
    public Object clone()
    {
        return new AAndLogicalOr(
            (PLogicalOr) cloneNode(_l_),
            (PLogicalOr) cloneNode(_r_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAndLogicalOr(this);
    }

    public PLogicalOr getL()
    {
        return _l_;
    }

    public void setL(PLogicalOr node)
    {
        if(_l_ != null)
        {
            _l_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _l_ = node;
    }

    public PLogicalOr getR()
    {
        return _r_;
    }

    public void setR(PLogicalOr node)
    {
        if(_r_ != null)
        {
            _r_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _r_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_l_)
            + toString(_r_);
    }

    void removeChild(Node child)
    {
        if(_l_ == child)
        {
            _l_ = null;
            return;
        }

        if(_r_ == child)
        {
            _r_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_l_ == oldChild)
        {
            setL((PLogicalOr) newChild);
            return;
        }

        if(_r_ == oldChild)
        {
            setR((PLogicalOr) newChild);
            return;
        }

    }
}
