/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AAsciiBase extends PBase
{
    private TAscii _ascii_;
    private TLPar _lPar_;
    private TId _id_;
    private TRPar _rPar_;

    public AAsciiBase()
    {
    }

    public AAsciiBase(
        TAscii _ascii_,
        TLPar _lPar_,
        TId _id_,
        TRPar _rPar_)
    {
        setAscii(_ascii_);

        setLPar(_lPar_);

        setId(_id_);

        setRPar(_rPar_);

    }
    public Object clone()
    {
        return new AAsciiBase(
            (TAscii) cloneNode(_ascii_),
            (TLPar) cloneNode(_lPar_),
            (TId) cloneNode(_id_),
            (TRPar) cloneNode(_rPar_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAsciiBase(this);
    }

    public TAscii getAscii()
    {
        return _ascii_;
    }

    public void setAscii(TAscii node)
    {
        if(_ascii_ != null)
        {
            _ascii_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _ascii_ = node;
    }

    public TLPar getLPar()
    {
        return _lPar_;
    }

    public void setLPar(TLPar node)
    {
        if(_lPar_ != null)
        {
            _lPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _lPar_ = node;
    }

    public TId getId()
    {
        return _id_;
    }

    public void setId(TId node)
    {
        if(_id_ != null)
        {
            _id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _id_ = node;
    }

    public TRPar getRPar()
    {
        return _rPar_;
    }

    public void setRPar(TRPar node)
    {
        if(_rPar_ != null)
        {
            _rPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _rPar_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_ascii_)
            + toString(_lPar_)
            + toString(_id_)
            + toString(_rPar_);
    }

    void removeChild(Node child)
    {
        if(_ascii_ == child)
        {
            _ascii_ = null;
            return;
        }

        if(_lPar_ == child)
        {
            _lPar_ = null;
            return;
        }

        if(_id_ == child)
        {
            _id_ = null;
            return;
        }

        if(_rPar_ == child)
        {
            _rPar_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_ascii_ == oldChild)
        {
            setAscii((TAscii) newChild);
            return;
        }

        if(_lPar_ == oldChild)
        {
            setLPar((TLPar) newChild);
            return;
        }

        if(_id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(_rPar_ == oldChild)
        {
            setRPar((TRPar) newChild);
            return;
        }

    }
}
