/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class ABaseFactor extends PFactor
{
    private PBase _base_;

    public ABaseFactor()
    {
    }

    public ABaseFactor(
        PBase _base_)
    {
        setBase(_base_);

    }
    public Object clone()
    {
        return new ABaseFactor(
            (PBase) cloneNode(_base_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABaseFactor(this);
    }

    public PBase getBase()
    {
        return _base_;
    }

    public void setBase(PBase node)
    {
        if(_base_ != null)
        {
            _base_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _base_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_base_);
    }

    void removeChild(Node child)
    {
        if(_base_ == child)
        {
            _base_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_base_ == oldChild)
        {
            setBase((PBase) newChild);
            return;
        }

    }
}
