/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class ABracketsExpBase extends PBase
{
    private TLBr _lBr_;
    private PValue _firstValue_;
    private final LinkedList _commaValue_ = new TypedLinkedList(new CommaValue_Cast());
    private TRBr _rBr_;

    public ABracketsExpBase()
    {
    }

    public ABracketsExpBase(
        TLBr _lBr_,
        PValue _firstValue_,
        List _commaValue_,
        TRBr _rBr_)
    {
        setLBr(_lBr_);

        setFirstValue(_firstValue_);

        {
            this._commaValue_.clear();
            this._commaValue_.addAll(_commaValue_);
        }

        setRBr(_rBr_);

    }
    public Object clone()
    {
        return new ABracketsExpBase(
            (TLBr) cloneNode(_lBr_),
            (PValue) cloneNode(_firstValue_),
            cloneList(_commaValue_),
            (TRBr) cloneNode(_rBr_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABracketsExpBase(this);
    }

    public TLBr getLBr()
    {
        return _lBr_;
    }

    public void setLBr(TLBr node)
    {
        if(_lBr_ != null)
        {
            _lBr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _lBr_ = node;
    }

    public PValue getFirstValue()
    {
        return _firstValue_;
    }

    public void setFirstValue(PValue node)
    {
        if(_firstValue_ != null)
        {
            _firstValue_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _firstValue_ = node;
    }

    public LinkedList getCommaValue()
    {
        return _commaValue_;
    }

    public void setCommaValue(List list)
    {
        _commaValue_.clear();
        _commaValue_.addAll(list);
    }

    public TRBr getRBr()
    {
        return _rBr_;
    }

    public void setRBr(TRBr node)
    {
        if(_rBr_ != null)
        {
            _rBr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _rBr_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_lBr_)
            + toString(_firstValue_)
            + toString(_commaValue_)
            + toString(_rBr_);
    }

    void removeChild(Node child)
    {
        if(_lBr_ == child)
        {
            _lBr_ = null;
            return;
        }

        if(_firstValue_ == child)
        {
            _firstValue_ = null;
            return;
        }

        if(_commaValue_.remove(child))
        {
            return;
        }

        if(_rBr_ == child)
        {
            _rBr_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_lBr_ == oldChild)
        {
            setLBr((TLBr) newChild);
            return;
        }

        if(_firstValue_ == oldChild)
        {
            setFirstValue((PValue) newChild);
            return;
        }

        for(ListIterator i = _commaValue_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(_rBr_ == oldChild)
        {
            setRBr((TRBr) newChild);
            return;
        }

    }

    private class CommaValue_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PCommaValue node = (PCommaValue) o;

            if((node.parent() != null) &&
                (node.parent() != ABracketsExpBase.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != ABracketsExpBase.this))
            {
                node.parent(ABracketsExpBase.this);
            }

            return node;
        }
    }
}
