/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class ABracketsExpExpression extends PExpression
{
    private PValue _value_;
    private final LinkedList _commaValue_ = new TypedLinkedList(new CommaValue_Cast());

    public ABracketsExpExpression()
    {
    }

    public ABracketsExpExpression(
        PValue _value_,
        List _commaValue_)
    {
        setValue(_value_);

        {
            this._commaValue_.clear();
            this._commaValue_.addAll(_commaValue_);
        }

    }
    public Object clone()
    {
        return new ABracketsExpExpression(
            (PValue) cloneNode(_value_),
            cloneList(_commaValue_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABracketsExpExpression(this);
    }

    public PValue getValue()
    {
        return _value_;
    }

    public void setValue(PValue node)
    {
        if(_value_ != null)
        {
            _value_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _value_ = node;
    }

    public LinkedList getCommaValue()
    {
        return _commaValue_;
    }

    public void setCommaValue(List list)
    {
        _commaValue_.clear();
        _commaValue_.addAll(list);
    }

    public String toString()
    {
        return ""
            + toString(_value_)
            + toString(_commaValue_);
    }

    void removeChild(Node child)
    {
        if(_value_ == child)
        {
            _value_ = null;
            return;
        }

        if(_commaValue_.remove(child))
        {
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_value_ == oldChild)
        {
            setValue((PValue) newChild);
            return;
        }

        for(ListIterator i = _commaValue_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

    }

    private class CommaValue_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PCommaValue node = (PCommaValue) o;

            if((node.parent() != null) &&
                (node.parent() != ABracketsExpExpression.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != ABracketsExpExpression.this))
            {
                node.parent(ABracketsExpExpression.this);
            }

            return node;
        }
    }
}
