/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AComparison extends PComparison
{
    private PLogicalOr _logicalOr_;

    public AComparison()
    {
    }

    public AComparison(
        PLogicalOr _logicalOr_)
    {
        setLogicalOr(_logicalOr_);

    }
    public Object clone()
    {
        return new AComparison(
            (PLogicalOr) cloneNode(_logicalOr_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAComparison(this);
    }

    public PLogicalOr getLogicalOr()
    {
        return _logicalOr_;
    }

    public void setLogicalOr(PLogicalOr node)
    {
        if(_logicalOr_ != null)
        {
            _logicalOr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _logicalOr_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_logicalOr_);
    }

    void removeChild(Node child)
    {
        if(_logicalOr_ == child)
        {
            _logicalOr_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_logicalOr_ == oldChild)
        {
            setLogicalOr((PLogicalOr) newChild);
            return;
        }

    }
}
