/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class ACommaModule extends PCommaModule
{
    private PModule _module_;

    public ACommaModule()
    {
    }

    public ACommaModule(
        PModule _module_)
    {
        setModule(_module_);

    }
    public Object clone()
    {
        return new ACommaModule(
            (PModule) cloneNode(_module_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACommaModule(this);
    }

    public PModule getModule()
    {
        return _module_;
    }

    public void setModule(PModule node)
    {
        if(_module_ != null)
        {
            _module_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _module_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_module_);
    }

    void removeChild(Node child)
    {
        if(_module_ == child)
        {
            _module_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_module_ == oldChild)
        {
            setModule((PModule) newChild);
            return;
        }

    }
}
