/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AExpression extends PExpression
{
    private PAdditiveExpression _additiveExpression_;

    public AExpression()
    {
    }

    public AExpression(
        PAdditiveExpression _additiveExpression_)
    {
        setAdditiveExpression(_additiveExpression_);

    }
    public Object clone()
    {
        return new AExpression(
            (PAdditiveExpression) cloneNode(_additiveExpression_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpression(this);
    }

    public PAdditiveExpression getAdditiveExpression()
    {
        return _additiveExpression_;
    }

    public void setAdditiveExpression(PAdditiveExpression node)
    {
        if(_additiveExpression_ != null)
        {
            _additiveExpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _additiveExpression_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_additiveExpression_);
    }

    void removeChild(Node child)
    {
        if(_additiveExpression_ == child)
        {
            _additiveExpression_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_additiveExpression_ == oldChild)
        {
            setAdditiveExpression((PAdditiveExpression) newChild);
            return;
        }

    }
}
