/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AFunctionBody extends PFunctionBody
{
    private final LinkedList _tab_ = new TypedLinkedList(new Tab_Cast());
    private final LinkedList _statement_ = new TypedLinkedList(new Statement_Cast());

    public AFunctionBody()
    {
    }

    public AFunctionBody(
        List _tab_,
        List _statement_)
    {
        {
            this._tab_.clear();
            this._tab_.addAll(_tab_);
        }

        {
            this._statement_.clear();
            this._statement_.addAll(_statement_);
        }

    }
    public Object clone()
    {
        return new AFunctionBody(
            cloneList(_tab_),
            cloneList(_statement_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFunctionBody(this);
    }

    public LinkedList getTab()
    {
        return _tab_;
    }

    public void setTab(List list)
    {
        _tab_.clear();
        _tab_.addAll(list);
    }

    public LinkedList getStatement()
    {
        return _statement_;
    }

    public void setStatement(List list)
    {
        _statement_.clear();
        _statement_.addAll(list);
    }

    public String toString()
    {
        return ""
            + toString(_tab_)
            + toString(_statement_);
    }

    void removeChild(Node child)
    {
        if(_tab_.remove(child))
        {
            return;
        }

        if(_statement_.remove(child))
        {
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        for(ListIterator i = _tab_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        for(ListIterator i = _statement_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

    }

    private class Tab_Cast implements Cast
    {
        public Object cast(Object o)
        {
            TTab node = (TTab) o;

            if((node.parent() != null) &&
                (node.parent() != AFunctionBody.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != AFunctionBody.this))
            {
                node.parent(AFunctionBody.this);
            }

            return node;
        }
    }

    private class Statement_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PStatement node = (PStatement) o;

            if((node.parent() != null) &&
                (node.parent() != AFunctionBody.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != AFunctionBody.this))
            {
                node.parent(AFunctionBody.this);
            }

            return node;
        }
    }
}
