/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AImportStatement extends PStatement
{
    private PImportStatement _importStatement_;

    public AImportStatement()
    {
    }

    public AImportStatement(
        PImportStatement _importStatement_)
    {
        setImportStatement(_importStatement_);

    }
    public Object clone()
    {
        return new AImportStatement(
            (PImportStatement) cloneNode(_importStatement_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAImportStatement(this);
    }

    public PImportStatement getImportStatement()
    {
        return _importStatement_;
    }

    public void setImportStatement(PImportStatement node)
    {
        if(_importStatement_ != null)
        {
            _importStatement_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _importStatement_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_importStatement_);
    }

    void removeChild(Node child)
    {
        if(_importStatement_ == child)
        {
            _importStatement_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_importStatement_ == oldChild)
        {
            setImportStatement((PImportStatement) newChild);
            return;
        }

    }
}
