/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class ANotLogicalNot extends PLogicalNot
{
    private TNot _not_;
    private PLogicalNot _logicalNot_;

    public ANotLogicalNot()
    {
    }

    public ANotLogicalNot(
        TNot _not_,
        PLogicalNot _logicalNot_)
    {
        setNot(_not_);

        setLogicalNot(_logicalNot_);

    }
    public Object clone()
    {
        return new ANotLogicalNot(
            (TNot) cloneNode(_not_),
            (PLogicalNot) cloneNode(_logicalNot_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANotLogicalNot(this);
    }

    public TNot getNot()
    {
        return _not_;
    }

    public void setNot(TNot node)
    {
        if(_not_ != null)
        {
            _not_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _not_ = node;
    }

    public PLogicalNot getLogicalNot()
    {
        return _logicalNot_;
    }

    public void setLogicalNot(PLogicalNot node)
    {
        if(_logicalNot_ != null)
        {
            _logicalNot_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _logicalNot_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_not_)
            + toString(_logicalNot_);
    }

    void removeChild(Node child)
    {
        if(_not_ == child)
        {
            _not_ = null;
            return;
        }

        if(_logicalNot_ == child)
        {
            _logicalNot_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_not_ == oldChild)
        {
            setNot((TNot) newChild);
            return;
        }

        if(_logicalNot_ == oldChild)
        {
            setLogicalNot((PLogicalNot) newChild);
            return;
        }

    }
}
