/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class ANotLogicalAnd extends PLogicalAnd
{
    private PLogicalNot _logicalNot_;

    public ANotLogicalAnd()
    {
    }

    public ANotLogicalAnd(
        PLogicalNot _logicalNot_)
    {
        setLogicalNot(_logicalNot_);

    }
    public Object clone()
    {
        return new ANotLogicalAnd(
            (PLogicalNot) cloneNode(_logicalNot_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANotLogicalAnd(this);
    }

    public PLogicalNot getLogicalNot()
    {
        return _logicalNot_;
    }

    public void setLogicalNot(PLogicalNot node)
    {
        if(_logicalNot_ != null)
        {
            _logicalNot_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _logicalNot_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_logicalNot_);
    }

    void removeChild(Node child)
    {
        if(_logicalNot_ == child)
        {
            _logicalNot_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_logicalNot_ == oldChild)
        {
            setLogicalNot((PLogicalNot) newChild);
            return;
        }

    }
}
