/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class APlusAdditiveExpression extends PAdditiveExpression
{
    private PAdditiveExpression _additiveExpression_;
    private TPlus _plus_;
    private PTerm _term_;

    public APlusAdditiveExpression()
    {
    }

    public APlusAdditiveExpression(
        PAdditiveExpression _additiveExpression_,
        TPlus _plus_,
        PTerm _term_)
    {
        setAdditiveExpression(_additiveExpression_);

        setPlus(_plus_);

        setTerm(_term_);

    }
    public Object clone()
    {
        return new APlusAdditiveExpression(
            (PAdditiveExpression) cloneNode(_additiveExpression_),
            (TPlus) cloneNode(_plus_),
            (PTerm) cloneNode(_term_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPlusAdditiveExpression(this);
    }

    public PAdditiveExpression getAdditiveExpression()
    {
        return _additiveExpression_;
    }

    public void setAdditiveExpression(PAdditiveExpression node)
    {
        if(_additiveExpression_ != null)
        {
            _additiveExpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _additiveExpression_ = node;
    }

    public TPlus getPlus()
    {
        return _plus_;
    }

    public void setPlus(TPlus node)
    {
        if(_plus_ != null)
        {
            _plus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _plus_ = node;
    }

    public PTerm getTerm()
    {
        return _term_;
    }

    public void setTerm(PTerm node)
    {
        if(_term_ != null)
        {
            _term_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _term_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_additiveExpression_)
            + toString(_plus_)
            + toString(_term_);
    }

    void removeChild(Node child)
    {
        if(_additiveExpression_ == child)
        {
            _additiveExpression_ = null;
            return;
        }

        if(_plus_ == child)
        {
            _plus_ = null;
            return;
        }

        if(_term_ == child)
        {
            _term_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_additiveExpression_ == oldChild)
        {
            setAdditiveExpression((PAdditiveExpression) newChild);
            return;
        }

        if(_plus_ == oldChild)
        {
            setPlus((TPlus) newChild);
            return;
        }

        if(_term_ == oldChild)
        {
            setTerm((PTerm) newChild);
            return;
        }

    }
}
