/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

public final class TAscii extends Token
{
    public TAscii()
    {
        super.setText("ascii");
    }

    public TAscii(int line, int pos)
    {
        super.setText("ascii");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TAscii(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTAscii(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TAscii text.");
    }
}
