/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

public final class TPlusEq extends Token
{
    public TPlusEq()
    {
        super.setText("+=");
    }

    public TPlusEq(int line, int pos)
    {
        super.setText("+=");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TPlusEq(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTPlusEq(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TPlusEq text.");
    }
}
